Jul-19 09:50:24.009 [main] DEBUG nextflow.cli.Launcher - $> nextflow run test_data_access.nf
Jul-19 09:50:24.066 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.4
Jul-19 09:50:24.146 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Jul-19 09:50:24.168 [main] INFO  nextflow.cli.CmdRun - Launching `test_data_access.nf` [friendly_mclean] DSL2 - revision: b29c1d9c4b
Jul-19 09:50:24.185 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/home/vinay/.nextflow/plugins; core-plugins: nf-amazon@1.7.2,nf-azure@0.13.2,nf-console@1.0.3,nf-ga4gh@1.0.3,nf-google@1.1.4,nf-sqldb@0.4.0,nf-tower@1.4.0
Jul-19 09:50:24.186 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jul-19 09:50:24.199 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jul-19 09:50:24.200 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jul-19 09:50:24.204 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jul-19 09:50:24.216 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jul-19 09:50:24.274 [main] DEBUG nextflow.Session - Session uuid: 561b34c5-757e-4991-903e-f37b85910ca4
Jul-19 09:50:24.274 [main] DEBUG nextflow.Session - Run name: friendly_mclean
Jul-19 09:50:24.276 [main] DEBUG nextflow.Session - Executor pool size: 12
Jul-19 09:50:24.313 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.04.4 build 5706
  Created: 19-06-2022 20:51 UTC (20-06-2022 02:21 IDT)
  System: Linux 5.10.16.3-microsoft-standard-WSL2
  Runtime: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.15+10-Ubuntu-0ubuntu0.20.04.1
  Encoding: UTF-8 (UTF-8)
  Process: 31812@APBANL-R90XW6ZM [127.0.1.1]
  CPUs: 12 - Mem: 24.8 GB (11.4 GB) - Swap: 7 GB (7 GB)
Jul-19 09:50:24.341 [main] DEBUG nextflow.Session - Work-dir: /home/vinay/nextflow-examples/work [ext2/ext3]
Jul-19 09:50:24.342 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/vinay/nextflow-examples/bin
Jul-19 09:50:24.350 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jul-19 09:50:24.363 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jul-19 09:50:24.389 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jul-19 09:50:24.402 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 13; maxThreads: 1000
Jul-19 09:50:24.485 [main] DEBUG nextflow.Session - Session start invoked
Jul-19 09:50:25.228 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jul-19 09:50:25.343 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Jul-19 09:50:25.343 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Jul-19 09:50:25.348 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Jul-19 09:50:25.355 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=12; memory=24.8 GB; capacity=12; pollInterval=100ms; dumpInterval=5m
Jul-19 09:50:25.540 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: pyTask, getDataOverExternalScript, getData, perlTask
Jul-19 09:50:25.541 [main] DEBUG nextflow.Session - Ignite dataflow network (1)
Jul-19 09:50:25.541 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > getDataOverExternalScript
Jul-19 09:50:25.542 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Jul-19 09:50:25.543 [main] DEBUG nextflow.Session - Session await
Jul-19 09:50:25.651 [Actor Thread 6] INFO  nextflow.conda.CondaCache - Creating env using conda: certifi pyarrow pandas [cache /home/vinay/nextflow-examples/work/conda/env-1b6d97d267c43eab06d269ed96044331]
Jul-19 09:51:34.105 [Actor Thread 6] DEBUG nextflow.conda.CondaCache - 'conda' create complete env=certifi pyarrow pandas path=/home/vinay/nextflow-examples/work/conda/env-1b6d97d267c43eab06d269ed96044331
Jul-19 09:51:34.189 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jul-19 09:51:34.200 [Task submitter] INFO  nextflow.Session - [be/e53b5c] Submitted process > getDataOverExternalScript
Jul-19 09:51:34.968 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: getDataOverExternalScript; status: COMPLETED; exit: 2; error: -; workDir: /home/vinay/nextflow-examples/work/be/e53b5c66834c7428f733ad9d39031b]
Jul-19 09:51:35.017 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'getDataOverExternalScript'

Caused by:
  Process `getDataOverExternalScript` terminated with an error exit status (2)

Command executed:

  python /home/vinay/get_data.py

Command exit status:
  2

Command output:
  (empty)

Command error:
  python: can't open file '/home/vinay/get_data.py': [Errno 2] No such file or directory

Work dir:
  /home/vinay/nextflow-examples/work/be/e53b5c66834c7428f733ad9d39031b

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
Jul-19 09:51:35.029 [main] DEBUG nextflow.Session - Session await > all process finished
Jul-19 09:51:35.030 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `getDataOverExternalScript` terminated with an error exit status (2)
Jul-19 09:51:35.066 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jul-19 09:51:35.078 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=712ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Jul-19 09:51:35.239 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Jul-19 09:51:35.250 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
